version: '3'

services:

  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=strongteam-news
    ports:
      - "5432:5436"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend


  app:
    image: 'strong-team-news:0.0.1'
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge